
/**
 *  
 *  @author Prof: J. Antonio Lemos B.
 *  
 *  Estructuras de Datos y Algoritmos 1, Grupo 1.
 *  Práctica del Corte 1.
 *  Fecha: Cali, Septiembre 10 de 2020.
 *
 */
package prc1_edya1_2020_03_gr1_nombreapellido;

import javax.swing.JOptionPane;
import java.text.DecimalFormat;

public class Empresa_GUI extends javax.swing.JFrame {
    // Atributos de la clase:
    private Empresa empresa;  
    private static boolean primeraVez = true;
    private DecimalFormat df;
    private long ti, deltaT;
    
    /**
     * Creates new form Curso_GUI
     */
    public Empresa_GUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "Convert2Lambda"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEntradas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Empresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_NIT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Cedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_antLab = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_ApeNom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_SMN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTF_BuscarEliminar = new javax.swing.JTextField();
        jPanelSalidas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTF_smnPromedio = new javax.swing.JTextField();
        jScrollPaneReporte = new javax.swing.JScrollPane();
        jTextAreaReporte = new javax.swing.JTextArea();
        jButton_Promedio = new javax.swing.JButton();
        jPanelAcciones = new javax.swing.JPanel();
        jButton_CrearEmpresa = new javax.swing.JButton();
        jButton_Limpiar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jButton_BuscarPorCedula = new javax.swing.JButton();
        jButton_EliminarPorCedula = new javax.swing.JButton();
        jButton_AgregarTrabajadores = new javax.swing.JButton();
        jB_SMN_Altos = new javax.swing.JButton();
        jButton_MostrarTrabajadores = new javax.swing.JButton();
        jB_DatosMayorSMN = new javax.swing.JButton();
        jButton_OrdenarPorApellidos = new javax.swing.JButton();
        jB_AportanBono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estructuras de Datos y Algoritmos 1 - Práctica del Corte 1, Prof: JALB.");
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N

        jPanelEntradas.setBackground(java.awt.Color.cyan);
        jPanelEntradas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entradas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanelEntradas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setBackground(java.awt.Color.yellow);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ingrese el nombre de la Empresa:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));

        jTextField_Empresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setBackground(java.awt.Color.yellow);
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Digite el NIT de la Empresa:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));

        jTextField_NIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setBackground(java.awt.Color.yellow);
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ingrese Apellidos y nombre del Trabajador:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));

        jTextField_Cedula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setBackground(java.awt.Color.yellow);
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("¿Cuántos años lleva en la Empresa?");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));

        jTextField_antLab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel5.setBackground(java.awt.Color.yellow);
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Digite la Cédula del Trabajador:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));

        jTextField_ApeNom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setBackground(java.awt.Color.yellow);
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Digite el SMN (Salario Mensual Nominal): $");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));

        jTextField_SMN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel10.setBackground(java.awt.Color.yellow);
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Digite la Cédula del Trabajador (para Buscarlo o para Eliminarlo):");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));

        jTF_BuscarEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanelEntradasLayout = new javax.swing.GroupLayout(jPanelEntradas);
        jPanelEntradas.setLayout(jPanelEntradasLayout);
        jPanelEntradasLayout.setHorizontalGroup(
            jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEntradasLayout.createSequentialGroup()
                        .addGroup(jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEntradasLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_NIT))
                            .addGroup(jPanelEntradasLayout.createSequentialGroup()
                                .addGroup(jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelEntradasLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_ApeNom, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelEntradasLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_SMN, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelEntradasLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_antLab, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(jPanelEntradasLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_BuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelEntradasLayout.setVerticalGroup(
            jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ApeNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_antLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_BuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSalidas.setBackground(java.awt.Color.cyan);
        jPanelSalidas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanelSalidas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel7.setBackground(java.awt.Color.yellow);
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Salario Mensual Nominal PROMEDIO: $ ");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));

        jTF_smnPromedio.setEditable(false);
        jTF_smnPromedio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextAreaReporte.setEditable(false);
        jTextAreaReporte.setBackground(new java.awt.Color(255, 255, 204));
        jTextAreaReporte.setColumns(20);
        jTextAreaReporte.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextAreaReporte.setRows(5);
        jTextAreaReporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jScrollPaneReporte.setViewportView(jTextAreaReporte);

        jButton_Promedio.setBackground(java.awt.Color.green);
        jButton_Promedio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Promedio.setText("Salario Mensual Nominal PROMEDIO");
        jButton_Promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PromedioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalidasLayout = new javax.swing.GroupLayout(jPanelSalidas);
        jPanelSalidas.setLayout(jPanelSalidasLayout);
        jPanelSalidasLayout.setHorizontalGroup(
            jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelSalidasLayout.createSequentialGroup()
                        .addComponent(jButton_Promedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_smnPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSalidasLayout.setVerticalGroup(
            jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_smnPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Promedio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAcciones.setBackground(java.awt.Color.cyan);
        jPanelAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanelAcciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton_CrearEmpresa.setBackground(java.awt.Color.green);
        jButton_CrearEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_CrearEmpresa.setText("Crear la Empresa");
        jButton_CrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearEmpresaActionPerformed(evt);
            }
        });

        jButton_Limpiar.setBackground(java.awt.Color.green);
        jButton_Limpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Limpiar.setText("Limpiar");
        jButton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimpiarActionPerformed(evt);
            }
        });

        jButton_Salir.setBackground(java.awt.Color.green);
        jButton_Salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        jButton_BuscarPorCedula.setBackground(java.awt.Color.green);
        jButton_BuscarPorCedula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_BuscarPorCedula.setText("Buscar por Cédula");
        jButton_BuscarPorCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarPorCedulaActionPerformed(evt);
            }
        });

        jButton_EliminarPorCedula.setBackground(java.awt.Color.green);
        jButton_EliminarPorCedula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_EliminarPorCedula.setText("Eliminar por Cédula");
        jButton_EliminarPorCedula.setEnabled(false);
        jButton_EliminarPorCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarPorCedulaActionPerformed(evt);
            }
        });

        jButton_AgregarTrabajadores.setBackground(java.awt.Color.green);
        jButton_AgregarTrabajadores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_AgregarTrabajadores.setText("Agregar Trabajadores");
        jButton_AgregarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarTrabajadoresActionPerformed(evt);
            }
        });

        jB_SMN_Altos.setBackground(java.awt.Color.green);
        jB_SMN_Altos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_SMN_Altos.setText("Salarios > Salario Base");
        jB_SMN_Altos.setEnabled(false);
        jB_SMN_Altos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SMN_AltosActionPerformed(evt);
            }
        });

        jButton_MostrarTrabajadores.setBackground(java.awt.Color.green);
        jButton_MostrarTrabajadores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_MostrarTrabajadores.setText("Mostrar Trabajadores");
        jButton_MostrarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MostrarTrabajadoresActionPerformed(evt);
            }
        });

        jB_DatosMayorSMN.setBackground(java.awt.Color.green);
        jB_DatosMayorSMN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_DatosMayorSMN.setText("Datos Mayor SMN");
        jB_DatosMayorSMN.setEnabled(false);
        jB_DatosMayorSMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_DatosMayorSMNActionPerformed(evt);
            }
        });

        jButton_OrdenarPorApellidos.setBackground(java.awt.Color.green);
        jButton_OrdenarPorApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_OrdenarPorApellidos.setText("Ordenar por Apellidos");
        jButton_OrdenarPorApellidos.setEnabled(false);
        jButton_OrdenarPorApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OrdenarPorApellidosActionPerformed(evt);
            }
        });

        jB_AportanBono.setBackground(java.awt.Color.green);
        jB_AportanBono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_AportanBono.setText("Aportan al Bono");
        jB_AportanBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AportanBonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAccionesLayout = new javax.swing.GroupLayout(jPanelAcciones);
        jPanelAcciones.setLayout(jPanelAccionesLayout);
        jPanelAccionesLayout.setHorizontalGroup(
            jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccionesLayout.createSequentialGroup()
                        .addComponent(jButton_CrearEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_AgregarTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_MostrarTrabajadores)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_BuscarPorCedula))
                    .addGroup(jPanelAccionesLayout.createSequentialGroup()
                        .addComponent(jB_AportanBono, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_SMN_Altos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_DatosMayorSMN)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_OrdenarPorApellidos)))
                .addGap(18, 18, 18)
                .addGroup(jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAccionesLayout.createSequentialGroup()
                        .addComponent(jButton_Limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Salir))
                    .addComponent(jButton_EliminarPorCedula))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelAccionesLayout.setVerticalGroup(
            jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_EliminarPorCedula, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_CrearEmpresa)
                        .addComponent(jButton_BuscarPorCedula)
                        .addComponent(jButton_AgregarTrabajadores)
                        .addComponent(jButton_MostrarTrabajadores)))
                .addGroup(jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccionesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Limpiar)
                            .addComponent(jB_SMN_Altos)
                            .addComponent(jB_DatosMayorSMN)
                            .addComponent(jButton_OrdenarPorApellidos)
                            .addComponent(jB_AportanBono)))
                    .addGroup(jPanelAccionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSalidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // Let's read your choice:
        String msj = (String)JOptionPane.showInputDialog( null, "Do you " + 
            "really want to exit? [Y/N]:", "Exit ?", 1, null, 
            new Object[] {"Y", "N"}, "N") ;        
        char exit = msj.charAt(0);     
        
        if( exit == 'N' )  return;
        
        // Show author's credits before exit:
        //String credits = "Implemented by: NAME(S), SURNAME(S)\nCity and Date:" +
            //" CALI, Day/Month/Year\nVersion's Number: 01";
        String credits = "Implemented by: J. Antonio, LemOs B.\nCity and Date:"
            + " CALI, 10/September/2020\nVersion's Number: 01";
        JOptionPane.showMessageDialog( null, credits, "Author's Credits", 1);
        System.exit(0);
    }//GEN-LAST:event_jButton_SalirActionPerformed
    
    private void jButton_CrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearEmpresaActionPerformed
        // TODO add your handling code here:
         if( primeraVez ) {
            empresa = crearEmpresa();
            if(empresa == null) return; // Salga del método.
            df = new DecimalFormat("0.00");
            jTextField_Empresa.setEditable(false);
            jTextField_NIT.setEditable(false);
            jButton_CrearEmpresa.setEnabled(false);    
            primeraVez = false;
        }   // if primeraVez
    }//GEN-LAST:event_jButton_CrearEmpresaActionPerformed
    
    private void jButton_BuscarPorCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarPorCedulaActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;        
        limpiar();
        String cedula;  // Cédula del trabajador buscado.
        cedula = this.obtenerTexto(jTF_BuscarEliminar).toUpperCase();
        if(cedula.equals("")) return;
        ti = System.nanoTime();
        String datos = empresa.buscarDatosTrabajador(cedula);
        deltaT = System.nanoTime() - ti;
        datos += "\nTiempo usado en la búsqueda = " + deltaT + " (ns)."; 
        jTextAreaReporte.setText( datos ) ;                
    }//GEN-LAST:event_jButton_BuscarPorCedulaActionPerformed

    @SuppressWarnings("UnnecessaryReturnStatement")
    private void jButton_EliminarPorCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarPorCedulaActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;        
        // *********************************************************************
        
        // *********************************************************************                                
    }//GEN-LAST:event_jButton_EliminarPorCedulaActionPerformed

    @SuppressWarnings("UnnecessaryReturnStatement")
    private void jButton_OrdenarPorApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OrdenarPorApellidosActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;        
        // *********************************************************************
        
        // *********************************************************************        
    }//GEN-LAST:event_jButton_OrdenarPorApellidosActionPerformed

    private void jButton_AgregarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarTrabajadoresActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;        
        Trabajador trab = this.crearTrabajador();
        if(trab == null) return;
        empresa.agregarTrabajador(trab);
        limpiar();
    }//GEN-LAST:event_jButton_AgregarTrabajadoresActionPerformed
    
    private void jButton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();        
    }//GEN-LAST:event_jButton_LimpiarActionPerformed
    
    public void limpiar() {
        jTextField_ApeNom.setText("");
        jTextField_Cedula.setText("");
        jTextField_antLab.setText("");
        jTextField_SMN.setText("");
        jTF_smnPromedio.setText("");        
        jTextAreaReporte.setText("");        
    }   // Fin limpiar()
    
    /*******************NO BORRAR*******************************************
    private void jB_CumplenDesempe�oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CumplenDesempe�oActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jB_CumplenDesempe�oActionPerformed
    *********************NO BORRAR***************************************/
    
    private void jB_SMN_AltosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SMN_AltosActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;
        double smnBase;
        try {
            do {
                smnBase = Double.parseDouble( JOptionPane.showInputDialog(
                    "Digite el SMN (Salario Mensual Nominal) BASE: $ ") ) ;
                if(smnBase < Trabajador.SMMLV) {
                    JOptionPane.showMessageDialog(null, smnBase + " está por " + 
                        "debajo del SMMLV", "Error SMN Base", 0);
                }   // if
            } while(smnBase < Trabajador.SMMLV);
        }
        catch(NumberFormatException nfe) {
            System.out.println(nfe);
            return; // Salga del método.
        }                
        jTextAreaReporte.setText(empresa.obtenerAltosSalarios(smnBase));            
    }//GEN-LAST:event_jB_SMN_AltosActionPerformed

    @SuppressWarnings("UnnecessaryReturnStatement")
    private void jButton_MostrarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MostrarTrabajadoresActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;
        // *********************************************************************
        jTextAreaReporte.setText(empresa.toString());
        // *********************************************************************            
    }//GEN-LAST:event_jButton_MostrarTrabajadoresActionPerformed

    @SuppressWarnings("UnnecessaryReturnStatement")
    private void jB_DatosMayorSMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_DatosMayorSMNActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;
        // *********************************************************************
        
        // *********************************************************************                
    }//GEN-LAST:event_jB_DatosMayorSMNActionPerformed

    @SuppressWarnings("UnnecessaryReturnStatement")
    private void jButton_PromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PromedioActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;
        // *********************************************************************
        jTF_smnPromedio.setText(empresa.calcularSMNpromedio()+"");
        // *********************************************************************
    }//GEN-LAST:event_jButton_PromedioActionPerformed

    @SuppressWarnings("UnnecessaryReturnStatement")
    private void jB_AportanBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AportanBonoActionPerformed
        // TODO add your handling code here:
        if( empresa == null || ! empresa.getArreglosCreados() ) return ;
        // *********************************************************************
        jTextAreaReporte.setText(empresa.quienesAportanAlBono());
        // *********************************************************************        
    }//GEN-LAST:event_jB_AportanBonoActionPerformed
    
    @SuppressWarnings("null")
    public String obtenerTexto( javax.swing.JTextField  caja ) {
        String textoCaja = "", msj;
        if( caja == null ) {
            msj = "La caja no ha sido creada (referencia null)";
            JOptionPane.showMessageDialog( null, msj, "", 0 ) ;
            System.out.println( msj ) ;
            return textoCaja ;
        }   // if
        int longTexto = caja.getText().trim().length();
        if( longTexto == 0 ) {
            //msj = "DEBE digitar la información solicitada en la caja " + 
                //caja.getName();
            msj = "¡ DEBE digitar la información solicitada en las cajas !" ; 
            JOptionPane.showMessageDialog( null, msj, "ERROR", 0 ) ;
            System.out.println( msj ) ;
            return textoCaja;
        }   // if
        textoCaja = caja.getText().trim();
        return textoCaja;
    }   //  String obtenerTexto( javax.swing.JTextField ) 
    
    private Empresa crearEmpresa(){
        Empresa miEmpresa = null;
        String nombreEmpresa;     // Nombre de la Empresa.
        String NITdeLaEmpresa;     // NIT de la Empresa.
        
        nombreEmpresa = this.obtenerTexto(jTextField_Empresa);
        if( nombreEmpresa.equals("") ) return null;
        
        NITdeLaEmpresa = this.obtenerTexto(jTextField_NIT);
        if( NITdeLaEmpresa.equals("") ) return null;
        
        miEmpresa = new Empresa( nombreEmpresa, NITdeLaEmpresa );
        return miEmpresa;
    }   // crearCurso()  
    
    private Trabajador crearTrabajador() {
        Trabajador unTrab = null;
        // Variables locales:        
        String cedula;          // Cédula del trabajador.
        String apeNom;          // Apellidos y Nombres del trabajador.
        int antLab;             // Antiguedad laboral.
        double smn;             // Salario mensual nominal.
             
        cedula = this.obtenerTexto(jTextField_Cedula ).toUpperCase() ;
        if( cedula.equals("") ) return null;
        
        apeNom = this.obtenerTexto( jTextField_ApeNom ).toUpperCase() ;
        if( apeNom.equals("") ) return null;
        
        String strAntLab = this.obtenerTexto(jTextField_antLab );
        if( strAntLab.equals("") ) return null;
        
        String strSMN = this.obtenerTexto(jTextField_SMN );
        if( strSMN.equals("") ) return null;
             
        // Las siguientes lecturas pueden generar una NumberFormatException; 
        // por tanto, se realizan con un try-catch:
        try {
            antLab = Integer.parseInt( strAntLab ) ;
            if( antLab < 0 ) return null;
            smn = Double.parseDouble( strSMN ) ;
            if( smn <= 0 ) return null;            
        }   // try
        catch( NumberFormatException  nfe ) {
            JOptionPane.showMessageDialog( null, nfe, 
                "Number Format Exception", 0 ) ;
            System.out.println( nfe ) ;
            return null;    // Salga del método con el valor null
        }   // catch        
        unTrab = new  Trabajador(cedula, apeNom, antLab, smn); 
        return unTrab;         
    }   // NO BORRAR: FIN DEL MÉTODO crearTrabajador( )
    
    
    // Método main( ... ):
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>        
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {                
                new Empresa_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_AportanBono;
    private javax.swing.JButton jB_DatosMayorSMN;
    private javax.swing.JButton jB_SMN_Altos;
    private javax.swing.JButton jButton_AgregarTrabajadores;
    private javax.swing.JButton jButton_BuscarPorCedula;
    private javax.swing.JButton jButton_CrearEmpresa;
    private javax.swing.JButton jButton_EliminarPorCedula;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JButton jButton_MostrarTrabajadores;
    private javax.swing.JButton jButton_OrdenarPorApellidos;
    private javax.swing.JButton jButton_Promedio;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelAcciones;
    private javax.swing.JPanel jPanelEntradas;
    private javax.swing.JPanel jPanelSalidas;
    private javax.swing.JScrollPane jScrollPaneReporte;
    private javax.swing.JTextField jTF_BuscarEliminar;
    private javax.swing.JTextField jTF_smnPromedio;
    private javax.swing.JTextArea jTextAreaReporte;
    private javax.swing.JTextField jTextField_ApeNom;
    private javax.swing.JTextField jTextField_Cedula;
    private javax.swing.JTextField jTextField_Empresa;
    private javax.swing.JTextField jTextField_NIT;
    private javax.swing.JTextField jTextField_SMN;
    private javax.swing.JTextField jTextField_antLab;
    // End of variables declaration//GEN-END:variables

}   // No borrar: Fin de la clase Empresa_GUI